name: Auto Update packages

on:
  schedule:
    - cron: "? 15 * * 0"

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdater:
    name: "Update composer packages"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RECTOR_ACCESS_TOKEN }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version-file: .php-version
          coverage: none
          tools: composer:v2

      - uses: "ramsey/composer-install@v3"
        with:
          working-directory: app

      # Automatically run composer upgrade
      - name: Upgrade dependencies
        id: composer-update
        run: composer update --no-ansi --no-interaction --no-scripts --no-install --no-audit --no-progress --ignore-platform-req=ext-*
        working-directory: app

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.RECTOR_ACCESS_TOKEN }}
          reviewers: 'dsdeboer'
          title: "[chore] Automatic scheduled composer upgrade"
          body: "chore: Automatic composer upgrade"
          commit-message: "[ci] Automatic composer upgrade"
          branch: "chore/scheduled-composer-upgrade"
