name: Auto fix common mistakes

on:
  pull_request: null

permissions:
  contents: write
  pull-requests: write

jobs:
  fixers:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.RECTOR_ACCESS_TOKEN }}

      - uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a
        with:
          php-version-file: .php-version
          coverage: none
          tools: composer:v2

      - uses: ramsey/composer-install@a2636af0004d1c0499ffca16ac0b4cc94df70565
        with:
          working-directory: app

      - uses: actions/cache@v4.2.3
        with:
          path: app/var/cache/rector
          key: ${{ runner.os }}-rector-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-rector-

      - run: vendor/bin/rector --ansi
        working-directory: app

      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403
        with:
          commit_message: '[rector] Rector fixes'
          commit_author: 'GitHub Action <actions@github.com>'
          commit_user_email: 'action@github.com'

      - uses: actions/cache@v4.2.3
        with:
          path: app/var/cache/ecs
          key: ${{ runner.os }}-ecs-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-ecs-

      - run: vendor/bin/ecs check --fix --output-format=checkstyle
        working-directory: app

      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403
        with:
          commit_message: '[ecs] Easy Coding Standard fixes'
          commit_author: 'GitHub Action <actions@github.com>'
          commit_user_email: 'action@github.com'

  linters:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.RECTOR_ACCESS_TOKEN }}

      - uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a
        with:
          php-version-file: .php-version
          coverage: none
          tools: composer:v2

      - uses: ramsey/composer-install@a2636af0004d1c0499ffca16ac0b4cc94df70565
        with:
          working-directory: app

      - name: "Composer normalize"
        run: composer --working-dir app normalize
      - name: "Composer validate"
        run: composer --working-dir app validate --strict
      - name: "Class leak detection"
        run: vendor/bin/class-leak check bin config src
        working-directory: app
      - name: "Dependency scanner"
        run: vendor/bin/composer-dependency-analyser
        working-directory: app
