name: Auto fix common mistakes

on:
  pull_request: null

jobs:
  fixers:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RECTOR_ACCESS_TOKEN }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version-file: .php-version
          coverage: none

      - uses: "ramsey/composer-install@v3"
        with:
          working-directory: app

      - uses: actions/cache@v4
        with:
          path: app/var/cache/rector
          key: ${{ runner.os }}-rector-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-rector-

      - run: vendor/bin/rector --ansi
        working-directory: app

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[rector] Rector fixes'
          commit_author: 'GitHub Action <actions@github.com>'
          commit_user_email: 'action@github.com'

      - uses: actions/cache@v4
        with:
          path: app/var/cache/ecs
          key: ${{ runner.os }}-ecs-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-ecs-

      - run: vendor/bin/ecs check --fix --output-format=checkstyle
        working-directory: app

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[ecs] Easy Coding Standard fixes'
          commit_author: 'GitHub Action <actions@github.com>'
          commit_user_email: 'action@github.com'

  linters:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RECTOR_ACCESS_TOKEN }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version-file: .php-version
          coverage: none

      - uses: "ramsey/composer-install@v3"
        with:
          working-directory: app

      - name: "Composer normalize"
        run: composer --working-dir app normalize
      - name: "Composer validate"
        run: composer --working-dir app validate --strict
      - name: "Class leak detection"
        run: vendor/bin/class-leak check bin config src
        working-directory: app
      - name: "Dependency scanner"
        run: vendor/bin/composer-dependency-analyser
        working-directory: app
