name: Auto Update packages

on:
  workflow_dispatch: ~

jobs:
  fixers:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RECTOR_ACCESS_TOKEN }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version-file: .php-version
          coverage: none
          tools: composer:v2

      - uses: "ramsey/composer-install@v3"
        with:
          working-directory: app

      # Automatically run composer upgrade
      - name: Upgrade dependencies
        id: composer-update
        run: echo "composer_output='$(composer update --no-ansi --no-interaction --no-scripts --no-install --no-audit --no-progress --ignore-platform-req=ext-* 2>&1)'" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "[chore] Automatic scheduled composer upgrade"
          commit-message: ${{ steps.composer-update.outputs.composer_output }}
          branch: "chore/scheduled-composer-upgrade"
