name: Auto Update packages

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdater:
    name: "Update composer packages"
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.RECTOR_ACCESS_TOKEN }}

      - uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401
        with:
          php-version-file: .php-version
          coverage: none
          tools: composer:v2

      - uses: ramsey/composer-install@57532f8be5bda426838819c5ee9afb8af389d51a
        with:
          working-directory: app

      # Automatically run composer upgrade
      - name: Upgrade dependencies
        run: composer update --no-ansi --no-interaction --no-scripts --no-install --no-audit --no-progress --ignore-platform-req=ext-*
        working-directory: app

      - name: Normalize composer
        run: composer normalize
        working-directory: app

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@dd2324fc52d5d43c699a5636bcf19fceaa70c284
        with:
          token: ${{ secrets.RECTOR_ACCESS_TOKEN }}
          title: "[chore] Automatic scheduled composer upgrade"
          body: "chore: Automatic composer upgrade"
          branch: "chore/scheduled-composer-upgrade"
