name: Auto Update packages

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdater:
    name: "Update composer packages"
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.RECTOR_ACCESS_TOKEN }}

      - uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e
        with:
          php-version-file: .php-version
          coverage: none
          tools: composer:v2

      - uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520
        with:
          working-directory: app

      # Automatically run composer upgrade
      - name: Upgrade dependencies
        run: composer update --no-ansi --no-interaction --no-scripts --no-install --no-audit --no-progress --ignore-platform-req=ext-*
        working-directory: app

      - name: Normalize composer
        run: composer normalize
        working-directory: app

      - uses: dsdeboer/composer-require-checker-action@1.0.0
        with:
          working-dir: app

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          token: ${{ secrets.RECTOR_ACCESS_TOKEN }}
          title: "[chore] Automatic scheduled composer upgrade"
          body: "chore: Automatic composer upgrade"
          branch: "chore/scheduled-composer-upgrade"
